### ISSUE TITLE
Patching hdf5small_cxx_hl_1.10.7.tar.gz for /bin/mv

### ISSUE THREAD

**Issue by ppiecuch** [grimbough/Rhdf5lib#57]
Hello Team,

When building a package under Gentoo Prefix environment (CentOS7/GCC 9.3) there is a problem with `/bin/mv ` hardcoded into `hdf5` configure:

```
...
creating src/H5pubconf.h
/bin/mv: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /apps/rocs/2020.08/prefix/lib/../lib64/libpt
hread.so.0)
...
```

There are only two occurrences of `/bin/mv` in configure that should be just `mv` (rest is just the regular `mv`) - would you consider patching hdf5small_cxx_hl_1.10.7.tar.gz with that change (I have tested the package with that change and it builds fine)?

Best regards
Pawel

**Comment by grimbough** [comment]
Hi @ppiecuch ,

Thanks for the report.  That config script actually comes from the HDF5 library itself, but I'm happy to patch the version we're distributing. 

Can you try installing the `hdf5-config` branch and seeing if that works on your system.  You can do that with:

```r
BiocManager::install('grimbough/Rhdf5lib', ref = 'hdf5-config')
```

**Comment by ppiecuch** [comment]
Thank you for trying to solve my problem. But pretty much the same result, because `/bin/mv` is still selected:

```
config.status: executing pubconf commands
/bin/mv
creating src/H5pubconf.h
mv2 one
/bin/mv: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /apps/rocs/2020.08/prefix/lib/../lib64/libpthread.so.0)
Post process src/libhdf5.settings
```

I would like to replace `/bin/mv` with `mv` always (rest of the `mv` calls in that file is not using `/bin` prefix)
For reference, there is ~50 `mv` calls in the file but only these two are `/bin/mv`
